name: deploy test
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup hugo
        run: |
            wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
            sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
            hugo version
        env:
            HUGO_VERSION: '0.73.0'
      - name: Build hugo
        run: hugo
